import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import QRCode from 'qrcode';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.join(__dirname,'..');const dist=path.join(root,'dist');const dataDir=path.join(root,'data');const mediaDir=path.join(dataDir,'media');
const siteFile=path.join(dataDir,'site.json');const promotionFile=path.join(dataDir,'promotions.json');fs.mkdirSync(mediaDir,{recursive:true});
const siteDefaults={siteName:'كل شيء بالمعقول',news:'تابعوا أحدث منشورات المحل',featured:'آخر المنشورات',surpriseTitle:'مفاجأتك بانتظارك 🎁',surpriseMessage:'امسح QR واكتشف مفاجأتك.',stats:{sales:0,products:0,customers:0,stock:0},links:[],updatedAt:new Date().toISOString()};
const promotionDefaults={settings:{enabled:true,title:'مفاجأتك بانتظارك 🎁',message:'امسح QR واكتشف مفاجأتك.',buttonText:'اكتشف جائزتي 🎁',attemptsPerVisitor:1,campaignStart:null,campaignEnd:null},prizes:[],plays:[],qrToken:'',beforeMedia:'',winMedia:'',beforeEnabled:true,winEnabled:true,updatedAt:null};
function load(file,fallback){try{return {...fallback,...JSON.parse(fs.readFileSync(file,'utf8'))};}catch{fs.writeFileSync(file,JSON.stringify(fallback,null,2));return structuredClone(fallback);}}
function save(file,value){const tmp=`${file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify({...value,updatedAt:new Date().toISOString()},null,2));fs.renameSync(tmp,file);}
let site=load(siteFile,siteDefaults),promotion=load(promotionFile,promotionDefaults);promotion.settings={...promotionDefaults.settings,...(promotion.settings||{})};if(!promotion.settings.buttonText)promotion.settings.buttonText='اكتشف جائزتي 🎁';if(!promotion.qrToken){promotion.qrToken=crypto.randomBytes(24).toString('hex');save(promotionFile,promotion);}
const sessions=new Map(),limits=new Map();const production=process.env.NODE_ENV==='production';const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||(production?'':'admin123');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.svg':'image/svg+xml'};const mediaTypes={'image/png':'png','image/jpeg':'jpg','image/gif':'gif','image/webp':'webp'};
const now=()=>Date.now(),newId=(p='id')=>`${p}_${crypto.randomBytes(8).toString('hex')}`;
function send(res,status,body,type='text/plain; charset=utf-8',extra={}){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin',...extra});res.end(body);}
function json(res,status,obj){send(res,status,JSON.stringify(obj),mime['.json']);}
function file(res,filePath){if(!fs.existsSync(filePath)||!fs.statSync(filePath).isFile())return false;const ext=path.extname(filePath).toLowerCase();send(res,200,fs.readFileSync(filePath),mime[ext]||'application/octet-stream');return true;}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>12_000_000){reject(new Error('Payload too large'));req.destroy();}});req.on('end',()=>resolve(s));req.on('error',reject);});}
function cookie(req,n){return req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${n}=`))?.split('=').slice(1).join('=');}
function setCookie(res,n,v,maxAge=86400){res.setHeader('Set-Cookie',`${n}=${v}; Path=/; HttpOnly; SameSite=Lax;${production?' Secure;':''} Max-Age=${maxAge}`);}
function auth(req){const t=cookie(req,'belma3qoul_session');return !!(t&&sessions.get(t)>now());}
function rate(req,key,max=10,window=60000){const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'x').split(',')[0];const k=key+':'+ip;const e=limits.get(k),t=now();if(!e||t-e.t>window){limits.set(k,{t,n:1});return true;}e.n++;return e.n<=max;}
function active(){const s=promotion.settings,t=now();return !!s.enabled&&(!s.campaignStart||t>=new Date(s.campaignStart).getTime())&&(!s.campaignEnd||t<=new Date(s.campaignEnd).getTime());}
function pick(){const a=promotion.prizes.filter(p=>p.enabled&&Number(p.remaining)>0);if(!a.length)return null;const total=a.reduce((n,p)=>n+Math.max(0,Number(p.weight)||0),0);if(total<=0)return a[Math.floor(Math.random()*a.length)];let r=Math.random()*total;for(const p of a){r-=Math.max(0,Number(p.weight)||0);if(r<=0)return p;}return a.at(-1);}
function result(p){return p?{id:p.prizeId,name:p.prizeName,type:p.prizeType,value:p.prizeValue,link:p.prizeLink||''}:null;}
function visitor(req){return cookie(req,'belma3qoul_visitor')||crypto.randomBytes(16).toString('hex');}
function mediaSave(data,type){const ext=mediaTypes[type];if(!ext)throw new Error('نوع الملف غير مدعوم');const raw=String(data||'').replace(/^data:[^;]+;base64,/,'');const b=Buffer.from(raw,'base64');if(!b.length||b.length>8*1024*1024)throw new Error('حجم الملف يجب أن يكون بين 1B و8MB');const name=`${crypto.randomBytes(12).toString('hex')}.${ext}`;fs.writeFileSync(path.join(mediaDir,name),b);return `/media/${name}`;}
function qrPage(){return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>المفاجأة - كل شيء بالمعقول</title></head><body><script>location.replace('/surprise?token='+encodeURIComponent(new URLSearchParams(location.search).get('token')||''));</script></body></html>`;}
setInterval(()=>{const t=now();for(const[k,v]of sessions)if(v<=t)sessions.delete(k);for(const[k,v]of limits)if(t-v.t>60000)limits.delete(k);},60000).unref();
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),p=decodeURIComponent(u.pathname);
if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,service:'belma3qoul-web',time:new Date().toISOString()});
if(req.method==='POST'&&p==='/api/auth/login'){if(!ADMIN_PASSWORD)return json(res,503,{ok:false,error:'ADMIN_PASSWORD غير مضبوط على الخادم'});if(!rate(req,'login',8))return json(res,429,{ok:false,error:'محاولات دخول كثيرة'});const b=JSON.parse(await body(req)||'{}');if(b.password!==ADMIN_PASSWORD)return json(res,401,{ok:false,error:'بيانات الدخول غير صحيحة'});const t=crypto.randomBytes(32).toString('hex');sessions.set(t,now()+86400000);setCookie(res,'belma3qoul_session',t);return json(res,200,{ok:true});}
if(req.method==='POST'&&p==='/api/auth/logout'){const t=cookie(req,'belma3qoul_session');sessions.delete(t);setCookie(res,'belma3qoul_session','',0);return json(res,200,{ok:true});}
if(req.method==='GET'&&p==='/api/auth/me')return json(res,200,{authenticated:auth(req)});
if(req.method==='GET'&&p==='/api/settings')return json(res,200,{...site,surpriseTitle:promotion.settings.title,surpriseMessage:promotion.settings.message});
if(req.method==='POST'&&p==='/api/settings'){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});const b=JSON.parse(await body(req)||'{}');for(const k of ['siteName','news','featured'])if(b[k]!==undefined)site[k]=String(b[k]);save(siteFile,site);return json(res,200,{ok:true,data:site});}
if(req.method==='GET'&&p==='/api/stats')return json(res,200,{...site.stats,qrScans:promotion.plays.length,winners:promotion.plays.filter(x=>x.prizeType!=='message').length,remainingPrizes:promotion.prizes.reduce((n,x)=>n+Math.max(0,Number(x.remaining)||0),0)});
if(req.method==='GET'&&p==='/api/promotion/public')return json(res,200,{active:active(),title:promotion.settings.title,message:promotion.settings.message,buttonText:promotion.settings.buttonText||'اكتشف جائزتي 🎁',attemptsPerVisitor:promotion.settings.attemptsPerVisitor,beforeMedia:promotion.beforeMedia,beforeEnabled:promotion.beforeEnabled,winMedia:promotion.winMedia,winEnabled:promotion.winEnabled});
if(req.method==='POST'&&p==='/api/promotion/play'){if(cookie(req,'belma3qoul_qr_access')!=='1')return json(res,403,{ok:false,error:'يجب مسح رمز QR للدخول إلى المفاجأة'});if(!active())return json(res,409,{ok:false,error:'لا توجد مسابقة نشطة حالياً'});if(!rate(req,'play',20))return json(res,429,{ok:false,error:'طلبات كثيرة، حاول بعد قليل'});const key=visitor(req),plays=promotion.plays.filter(x=>x.visitorKey===key),limit=Math.max(1,Number(promotion.settings.attemptsPerVisitor)||1);if(plays.length>=limit){const old=plays.at(-1);return json(res,429,{ok:false,error:'لقد استنفدت محاولتك',play:{id:old.id,prize:result(old)}});}const prize=pick();if(!prize)return json(res,409,{ok:false,error:'انتهت جميع الجوائز'});prize.remaining=Math.max(0,Number(prize.remaining)-1);const play={id:newId('play'),visitorKey:key,prizeId:prize.id,prizeName:prize.name,prizeType:prize.type,prizeValue:prize.value,prizeLink:prize.link||'',createdAt:new Date().toISOString(),claimed:false};promotion.plays.push(play);save(promotionFile,promotion);setCookie(res,'belma3qoul_visitor',key,31536000);return json(res,200,{ok:true,play:{id:play.id,prize:result(play)}});}
if(req.method==='GET'&&p==='/api/qr'){const target=`${u.origin}/surprise?token=${encodeURIComponent(promotion.qrToken)}`;const png=await QRCode.toBuffer(target,{type:'png',width:512,margin:2,errorCorrectionLevel:'H'});return send(res,200,png,'image/png',{'Content-Length':png.length,'Cache-Control':'public,max-age=300'});}
if(req.method==='GET'&&p==='/qr-result'){if(u.searchParams.get('token')!==promotion.qrToken)return send(res,403,'QR غير صالح','text/plain; charset=utf-8');setCookie(res,'belma3qoul_qr_access','1',600);return send(res,302,'','text/plain; charset=utf-8',{Location:`/surprise?token=${encodeURIComponent(promotion.qrToken)}`});}
if(req.method==='GET'&&p==='/surprise'&&!u.searchParams.get('token'))return send(res,302,'','text/plain; charset=utf-8',{Location:'/#qr'});
if(req.method==='GET'&&p==='/surprise'&&u.searchParams.get('token')===promotion.qrToken)setCookie(res,'belma3qoul_qr_access','1',600);
if(req.method==='GET'&&p==='/api/admin/promotion'){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});return json(res,200,promotion);}
if(req.method==='PUT'&&p==='/api/admin/promotion/settings'){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});const b=JSON.parse(await body(req)||'{}');for(const k of ['enabled','title','message','buttonText','attemptsPerVisitor','campaignStart','campaignEnd'])if(b[k]!==undefined){if(k==='attemptsPerVisitor')promotion.settings[k]=Math.max(1,Number(b[k])||1);else if(k==='buttonText')promotion.settings[k]=String(b[k]);else promotion.settings[k]=b[k];}for(const k of ['beforeEnabled','winEnabled'])if(b[k]!==undefined)promotion[k]=!!b[k];save(promotionFile,promotion);return json(res,200,{ok:true,data:promotion.settings,beforeMedia:promotion.beforeMedia,winMedia:promotion.winMedia,beforeEnabled:promotion.beforeEnabled,winEnabled:promotion.winEnabled});}
if(req.method==='POST'&&p==='/api/admin/promotion/media'){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});const b=JSON.parse(await body(req)||'{}');if(!['before','win'].includes(b.kind))return json(res,400,{ok:false,error:'نوع الوسائط غير صحيح'});const url=mediaSave(b.data,b.mime);if(b.kind==='before')promotion.beforeMedia=url;else promotion.winMedia=url;save(promotionFile,promotion);return json(res,200,{ok:true,url});}
if(req.method==='POST'&&p==='/api/admin/prizes'){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});const b=JSON.parse(await body(req)||'{}'),q=Math.max(0,Number(b.quantity)||0),prize={id:newId('prize'),name:String(b.name||'جائزة جديدة'),type:String(b.type||'message'),value:String(b.value||''),quantity:q,remaining:q,enabled:b.enabled!==false,weight:Math.max(0,Number(b.weight)||0),link:String(b.link||'')};promotion.prizes.push(prize);save(promotionFile,promotion);return json(res,201,{ok:true,data:prize});}
if(req.method==='PUT'&&p.startsWith('/api/admin/prizes/')){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});const prize=promotion.prizes.find(x=>x.id===p.split('/').at(-1));if(!prize)return json(res,404,{ok:false,error:'Prize not found'});const b=JSON.parse(await body(req)||'{}');for(const k of ['name','type','value','link'])if(b[k]!==undefined)prize[k]=String(b[k]);if(b.enabled!==undefined)prize.enabled=!!b.enabled;if(b.weight!==undefined)prize.weight=Math.max(0,Number(b.weight)||0);if(b.quantity!==undefined){const q=Math.max(0,Number(b.quantity)||0),used=Math.max(0,Number(prize.quantity)-Number(prize.remaining));prize.quantity=q;prize.remaining=Math.max(0,q-used);}save(promotionFile,promotion);return json(res,200,{ok:true,data:prize});}
if(req.method==='DELETE'&&p.startsWith('/api/admin/prizes/')){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});promotion.prizes=promotion.prizes.filter(x=>x.id!==p.split('/').at(-1));save(promotionFile,promotion);return json(res,200,{ok:true});}
if(req.method==='GET'&&p==='/api/admin/plays'){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});return json(res,200,promotion.plays.slice().reverse());}
if(req.method==='PUT'&&p.startsWith('/api/admin/plays/')){if(!auth(req))return json(res,401,{ok:false,error:'Unauthorized'});const play=promotion.plays.find(x=>x.id===p.split('/').at(-1));if(!play)return json(res,404,{ok:false,error:'Play not found'});const b=JSON.parse(await body(req)||'{}');if(b.claimed!==undefined)play.claimed=!!b.claimed;save(promotionFile,promotion);return json(res,200,{ok:true,data:play});}
if(p.startsWith('/media/')){const name=path.basename(p),f=path.join(mediaDir,name);if(file(res,f))return;return send(res,404,'Not found');}
const safe=path.normalize(p).replace(/^([.][.][\\/])+/,''),f=path.join(dist,safe);if(p!=='/'&&file(res,f))return;if(file(res,path.join(dist,'index.html')))return;return send(res,503,'Production build not found');
}catch(e){return json(res,500,{ok:false,error:e.message||'Server error'});}});
const port=Number(process.env.PORT)||3000;server.listen(port,'0.0.0.0',()=>console.log(`belma3qoul-web running on ${port}`));